### ISSUE TITLE
Missing "

### ISSUE THREAD

**Issue by jamal-ali1989** [canonical/Ubuntu-Sans-fonts#119] opened 2024-08-01 22:24 UTC
I have tested this with practically every latest ubuntu font. The character İ am referring to is this one: https://en.wikipedia.org/wiki/%C6%8F

Ubuntu fonts do have this character's uppercase version, which works fine.
However, when I type its lowercase version, I either get an unknown character symbol or I get its capital form.
Is the lowercare version also going to get added in the future? There are a few languages that use this character.
The missing character's unicode value U0259 (lowercase version). However, it automatically defaults to U018F (uppercase version) specifically on Ubuntu fonts.

**Comment by djrrb** [comment] 2024-08-02 02:21
This appears to be a duplicate of #120 .

**Closed as completed by djrrb** 2024-08-02 02:21 UTC
